// Login Loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';
export const SIGNUP_ENABLE_LOADER = 'SIGNUP_ENABLE_LOADER';
export const SIGNUP_DISABLE_LOADER = 'SIGNUP_DISABLE_LOADER';
export const FORGOTPASS_ENABLE_LOADER = 'FORGOTPASS_ENABLE_LOADER';
export const FORGOTPASS_DISABLE_LOADER = 'FORGOTPASS_DISABLE_LOADER';
export const MEETING_ENABLE_LOADER = 'MEETING_ENABLE_LOADER';
export const MEETING_DISABLE_LOADER = 'MEETING_DISABLE_LOADER';
export const MEETING_BY_DATE_ENABLE_LOADER = 'MEETING_BY_DATE_ENABLE_LOADER';
export const MEETING_BY_DATE_DISABLE_LOADER = 'MEETING_BY_DATE_DISABLE_LOADER';

// Theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';

// ForgotPassword
export const FORGOTPASS_REQUEST = 'FORGOTPASS_REQUEST';
export const FORGOTPASS_RESPONSE = 'FORGOTPASS_RESPONSE';
export const FORGOTPASS_FAILED = 'FORGOTPASS_FAILED';
export const FORGOTPASS_NULL = 'FORGOTPASS_NULL';

// SignUp
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_RESPONSE = 'SIGNUP_RESPONSE';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNUP_NULL = 'SIGNUP_NULL';

// Option
export const OPTION_REQUEST = 'OPTION_REQUEST';

// Get account
export const GET_USER_ACCOUNT = 'GET_USER_ACCOUNT';
export const USER_ACCOUNT_RESPONSE = 'USER_ACCOUNT_RESPONSE';

// Refresh token
export const REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST';

// Meeting
export const REQUEST_MEETING = 'REQUEST_MEETING';
export const MEETING_RESPONSE = 'MEETING_RESPONSE';
export const MEETING_FAILED = 'MEETING_FAILED';

// Meeting by date
export const REQUEST_MEETING_BY_DATE = 'REQUEST_MEETING_BY_DATE';
export const MEETING_BY_DATE_RESPONSE = 'MEETING_BY_DATE_RESPONSE';
export const MEETING_BY_DATE_FAILED = 'MEETING_BY_DATE_FAILED';
