// Login Loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// Theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';

// ForgotPassword
export const FORGOTPASS_REQUEST = 'FORGOTPASS_REQUEST';
export const FORGOTPASS_RESPONSE = 'FORGOTPASS_RESPONSE';
export const FORGOTPASS_FAILED = 'FORGOTPASS_FAILED';

// Loaders
export const FORGOTPASS_ENABLE_LOADER = 'FORGOTPASS_ENABLE_LOADER';
export const FORGOTPASS_DISABLE_LOADER = 'FORGOTPASS_DISABLE_LOADER';

// SignUp
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_RESPONSE = 'SIGNUP_RESPONSE';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

// SignUp Loaders
export const SIGNUP_ENABLE_LOADER = 'SIGNUP_ENABLE_LOADER';
export const SIGNUP_DISABLE_LOADER = 'SIGNUP_DISABLE_LOADER';

// Option
export const OPTION_REQUEST = 'OPTION_REQUEST';
